/* DO NOT EDIT: this file was automatically generated by airtable-ts-codegen */
/* eslint-disable */
import type { Item, Table } from 'airtable-ts';

export interface Submission extends Item {
  id: string,
  projectName: string | null, // Original field: "Project Name"
  creator: string | null, // Original field: "Creator"
  description: string | null, // Original field: "Description"
  githubLink: string | null, // Original field: "Github Link"
}

export const submissionsTable: Table<Submission> = {
  name: 'Submissions',
  baseId: 'appnBo5fTRIovW4tQ',
  tableId: 'tblGiCzHhbCUcQk6H',
  mappings: {
    projectName: 'fldcldZ4a6dsGsPDx', // Original field: "Project Name"
    creator: 'fldcy1VuO81xgeFzL', // Original field: "Creator"
    description: 'fldd5h6U3cZ5PHRN9', // Original field: "Description"
    githubLink: 'fld8e8C8iVtmvKCCg', // Original field: "Github Link"
  },
  schema: {
    projectName: 'string | null',
    creator: 'string | null',
    description: 'string | null',
    githubLink: 'string | null',
  },
};